### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by willamesoares** [fgborja/CivisAnalysis#1]
Hi, I'm working on my final bachelor thesis and I found it really interesting this proposal on a Data Visualization tool.

Since I'm also working on a Data Visualization project, I'm willing to try your app and get some practice on the area.
Have you heard about Docker? I normally use it in order to run applications locally and I would like to know if you are interested in getting it setup in your application. I could work on it and send a pull request.

Let me know what you think.

Thanks and congrats for the project.

**Comment by fgborja** [comment]
Sure let's talk! 

Currently im working in a startup so if you are interested in future works / research on CivisAnalysis idea look for Rodrigo Moni (rnmsilva@inf.ufrgs.br, rodrigo.moni@inf.ufrgs.br) he is a master's student at UFRGS and have some related work going on.

The app is running at http://www.inf.ufrgs.br/~fgborja/civisanalysis2/ 
(Old version with correlation graphs -> http://www.inf.ufrgs.br/~fgborja/civis3/)

You can run the app locally:.. 
- In the /public folder run in terminal 'python -m SimpleHTTPServer'.
-- OR --
- install the npm modules 'npm install'
- run the grunt 'grunt serve'
The grunt will open http://localhost:9000/ with auto-relaod when editing js/css and compiling the .jade files.

Sorry for the unstructured codes :/ it was my first web/js experience
Have fun!

**Comment by willamesoares** [comment]
Thanks for the interest!

Well, I have a pull request ready with the Dockerfile settings and some info about how to run the project with or without Docker. I will add the info you provided and submit it today.

I am very interested in helping with some issues you may have for this project or for some other related work. I'll contact Rodrigo Moni so we can see what I could help you guys with.

Thank you for all the information provided.
